name: Autoprefixer
on:
  push:
    branches:
      - master
jobs:
  autoprefixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "15.x"

      - name: Run autoprefixer
        run: |
          npm install postcss-cli autoprefixer --save-dev
          npm run autoprefixer
